zuul:
    prefix: /recipe
    routes:
      ingredient-service:
        path: /ingredient/**
        url: http://localhost:9092/ingredient
      recipe-service:
        path: /recipe/**
        url: http://localhost:9093/recipe
      user-service:
        path: /user/**
        url: http://localhost:9094/user